name: Java App CI/CD

on:
  workflow_dispatch:
    inputs:
      dev_env:
        description: 'Deploy to Dev'
        required: false

jobs:
  dev_build:
    name: Deploy to Dev 
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Amazon ECR
      run: |
        aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 422723218561.dkr.ecr.ap-south-1.amazonaws.com/githubaction
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}   
