name: Java App CI/CD

on:
  workflow_dispatch:
    inputs:
      dev_env:
        description: 'Deploy to Dev'
        required: false

jobs:
  dev_build:
    name: Deploy to Dev 
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

   
