name: Java App CI/CD

on:
  workflow_dispatch:
    inputs:
      dev_env:
        description: 'Deploy to Dev'
        required: true
      stage_env:
        description: 'Deploy to Stage'
        required: true
      prod_env:
        description: 'Deploy to Prod'
        required: true

jobs:
  dev_build:
    name: Deploy to Dev 
    runs-on: ubuntu-latest
    if:
      contains(github.event.inputs.dev_env, 'true')

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

   
